import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const baseURL = process.env.WORKSPACE_SVELTE_URL ?? 'http://127.0.0.1:5199';
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext(); const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => { window.workspaceEvents = []; for (const name of ['page-mounted', 'page-destroyed']) window.addEventListener(name, event => window.workspaceEvents.push([name, event.detail])); });
  await page.goto(baseURL);
  const menu = page.getByRole('navigation', { name: 'Screens' });
  await menu.getByRole('button', { name: 'Orders', exact: true }).click();
  await page.getByLabel('orders input', { exact: true }).fill('Retained');
  await page.getByRole('button', { name: 'Count 0', exact: true }).click();
  await menu.getByRole('button', { name: 'Customers', exact: true }).click();
  const inactive = page.locator('[data-workspace-part="panel"]').filter({ has: page.getByRole('heading', { name: 'orders page', includeHidden: true }) });
  await expect(inactive).toHaveAttribute('hidden', ''); await expect(inactive).toHaveAttribute('inert', '');
  await expect(inactive).toHaveCSS('display', 'none'); expect(await inactive.evaluate(element => element.getBoundingClientRect().height)).toBe(0);
  await expect(page.locator('[data-workspace-part="panel"]:not([hidden])')).toHaveCSS('display', 'flex');
  await page.getByRole('tab', { name: 'Orders', exact: true }).click();
  await expect(page.getByLabel('orders input', { exact: true })).toHaveValue('Retained');
  await expect(page.getByRole('button', { name: 'Count 1', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Deny customers', exact: true }).click();
  await page.getByRole('tab', { name: 'Customers', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Screen transition cancelled');
  await expect(page.getByRole('tab', { name: 'Orders', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByLabel('orders input', { exact: true })).toBeVisible();
  await expect(page.getByRole('tab', { name: 'Orders', exact: true })).toHaveClass(/custom-tab/);
  const deniedTrigger = page.getByRole('button', { name: 'Switch screens', exact: true }); await deniedTrigger.click();
  const deniedChoice = page.getByRole('dialog').getByRole('button', { name: 'Customers', exact: true }); await deniedChoice.click();
  await expect(page.getByRole('dialog')).toBeVisible(); await expect(deniedChoice).toBeFocused();
  await expect(page.getByRole('dialog').getByRole('status')).toHaveText('Screen transition cancelled');
  await expect(page.getByRole('status')).toHaveCount(1);
  await page.keyboard.press('Escape'); await expect(deniedTrigger).toBeFocused();
  await page.getByRole('button', { name: 'Allow customers', exact: true }).click();
  const orders = page.getByRole('tab', { name: 'Orders', exact: true }); await orders.focus(); await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('tab', { name: 'Customers', exact: true })).toBeFocused(); await expect(orders).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Enter'); await expect(page.getByRole('tab', { name: 'Customers', exact: true })).toHaveAttribute('aria-selected', 'true');
  const trigger = page.getByRole('button', { name: 'Switch screens', exact: true }); await trigger.click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.locator('[data-workspace-choice]').filter({ hasText: 'Customers' })).toBeFocused();
  for (let i = 0; i < 6; i++) { await page.keyboard.press('Tab'); expect(await page.evaluate(() => Boolean(document.activeElement?.closest('[role="dialog"]')))).toBe(true); }
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(trigger).toBeFocused();
  await page.getByRole('button', { name: 'Close Orders', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Orders', exact: true })).toHaveCount(0);
  await menu.getByRole('button', { name: 'Orders', exact: true }).click();
  await expect(page.getByLabel('orders input', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Reset workspace', exact: true }).click();
  await expect(page.getByRole('tab')).toHaveCount(0); await expect(trigger).toBeDisabled();
  const events = await page.evaluate(() => window.workspaceEvents); expect(events.filter(([name,id])=>name === 'page-mounted' && id === 'orders')).toHaveLength(2); expect(events.filter(([name,id])=>name === 'page-destroyed' && id === 'orders')).toHaveLength(2);
  await menu.getByRole('button', { name: 'Orders', exact: true }).click(); await page.getByLabel('orders input', { exact: true }).fill('Discarded');
  await page.getByRole('button', { name: 'Reset and reopen orders', exact: true }).click(); await expect(page.getByLabel('orders input', { exact: true })).toHaveValue('');
  await page.getByLabel('orders input', { exact: true }).focus(); await page.keyboard.press('Alt+q'); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('tab',{ name:'Orders',exact:true }).focus(); await page.keyboard.press('Alt+q'); await expect(page.getByRole('dialog')).toBeVisible(); await page.keyboard.press('Escape');
  for (const width of [1280, 390]) { await page.setViewportSize({width,height:800}); await menu.getByRole('button',{name:'Orders',exact:true}).click(); const result=await new AxeBuilder({page}).analyze(); expect(result.violations).toEqual([]); await trigger.click(); const modalResult=await new AxeBuilder({page}).analyze(); expect(modalResult.violations).toEqual([]); await page.keyboard.press('Escape'); }
  await page.goto(new URL('/?composition', baseURL).href); await expect(page.getByTestId('refs')).toHaveText('ready');
  await expect(page.getByTestId('custom-tab')).toHaveAttribute('role', 'tab'); await expect(page.getByTestId('custom-tab')).toHaveClass(/custom-tab/);
  await page.getByTestId('custom-tab').click(); await expect(page.getByTestId('clicks')).toHaveText('1');
  await page.getByTestId('custom-trigger').click(); await expect(page.getByRole('dialog')).toBeVisible(); await expect(page.getByTestId('clicks')).toHaveText('2');
  await page.keyboard.press('Escape'); await expect(page.getByTestId('custom-trigger')).toBeFocused();
  await page.getByTestId('custom-close').click(); await expect(page.getByTestId('clicks')).toHaveText('3'); await expect(page.getByRole('heading',{name:'orders page'})).toHaveCount(0);
  expect(errors).toEqual([]); console.log('Svelte native browser retention, cleanup, reset/reopen, guard denial/modal feedback, manual tabs, scoped shortcuts, dialog focus/trap, composition refs/events and 1280/390px axe checks passed');
} finally { await browser.close(); }
