import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('headless custom buttons preserve refs, events, guards and fresh instance identity', async ({ page }) => {
  await page.goto('/tests/fixtures/solid-headless.html');
  await page.addStyleTag({ content: '[data-workspace-part="panel"]{display:flex}' });
  await expect(page.locator('[data-workspace-part="panel"][hidden]')).toHaveCSS('display', 'none');
  await expect(page.locator('[data-workspace-part="panel"]:not([hidden])')).toHaveCSS('display', 'flex');
  const alpha = page.getByRole('tab', { name: 'Alpha', exact: true });
  const beta = page.getByRole('tab', { name: 'Beta', exact: true });
  expect(await page.evaluate(() => Object.values((window as any).harness.refs).every(node => (node as HTMLElement).isConnected))).toBe(true);
  expect(await page.evaluate(() => Object.keys((window as any).harness.refs).length)).toBe(5);
  await expect(alpha).toHaveClass('custom-tab');
  await page.getByLabel('Alpha draft', { exact: true }).fill('Retained');
  await page.evaluate(() => { (window as any).harness.deny = true; });
  await beta.click(); await expect(alpha).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('status')).toHaveText('Screen transition cancelled');
  const trigger = page.getByRole('button', { name: 'Switch screens', exact: true }); await trigger.click();
  const dialog = page.getByRole('dialog'); await dialog.getByRole('button', { name: 'Beta', exact: true }).click();
  await expect(dialog.getByRole('status')).toHaveText('Screen transition cancelled'); await expect(dialog).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.keyboard.press('Escape'); await expect(trigger).toBeFocused();
  await page.evaluate(() => { (window as any).harness.deny = false; (window as any).harness.pending = true; });
  await beta.click(); await expect(alpha).toHaveAttribute('aria-selected', 'true');
  await page.evaluate(() => { (window as any).harness.resolve(false); (window as any).harness.pending = false; });
  await expect(page.getByLabel('Alpha draft', { exact: true })).toHaveValue('Retained');
  await page.evaluate(() => { (window as any).harness.protect = true; });
  await alpha.focus(); await page.keyboard.press('Delete'); await expect(alpha).toBeVisible();
  await page.getByRole('button', { name: 'Close Alpha', exact: true }).click(); await expect(alpha).toBeVisible();
  expect(await page.evaluate(() => (window as any).harness.keys > 0 && (window as any).harness.clicks >= 2)).toBe(true);
  await page.evaluate(async () => { const api = (window as any).workspace; api.reset(); await api.open('a'); });
  await expect(page.getByLabel('Alpha draft', { exact: true })).toHaveValue('');
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
});
