import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('order filters and selection survive switching, with both demo themes accessible', async ({ page }) => {
  await page.goto('/');
  const tab = page.getByRole('tab', { name: 'Orders', exact: true });
  const close = page.getByRole('button', { name: 'Close Orders', exact: true });
  const tabBox = await tab.boundingBox();
  const closeBox = await close.boundingBox();
  expect(tabBox).not.toBeNull(); expect(closeBox).not.toBeNull();
  expect(closeBox!.x).toBeCloseTo(tabBox!.x + tabBox!.width, 1);
  expect(closeBox!.height).toBeCloseTo(tabBox!.height, 1);
  const tabColor = await tab.evaluate(element => getComputedStyle(element).backgroundColor);
  await expect(close).toHaveCSS('background-color', tabColor);
  const switcher = page.getByRole('button', { name: 'Open screens', exact: true });
  await expect(switcher).toHaveText('');
  await expect(switcher).toHaveAttribute('title', /열린 화면/);
  await page.getByLabel('Find an order').fill('Northline');
  await page.getByLabel('Select WS-1042').check();
  await page.getByRole('navigation', { name: 'Screens', exact: true }).getByRole('button', { name: 'Notes', exact: true }).click();
  await page.getByRole('tab', { name: 'Orders', exact: true }).click();
  const notesBox = await page.getByRole('tab', { name: 'Notes', exact: true }).boundingBox();
  const switcherBox = await switcher.boundingBox();
  const joinedTabBox = await tab.boundingBox();
  const joinedCloseBox = await close.boundingBox();
  expect(notesBox!.x).toBeCloseTo(joinedCloseBox!.x + joinedCloseBox!.width, 1);
  expect(joinedTabBox!.x).toBeCloseTo(switcherBox!.x + switcherBox!.width, 1);
  await expect(tab).toHaveCSS('border-radius', '0px');
  await expect(close).toHaveAttribute('data-active', 'true');
  await expect(tab).toHaveCSS('background-color', await page.getByRole('tabpanel', { name: 'Orders', exact: true }).evaluate(element => getComputedStyle(element).backgroundColor));
  await expect(page.getByLabel('Find an order')).toHaveValue('Northline');
  await expect(page.getByLabel('Select WS-1042')).toBeChecked();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.getByRole('button', { name: 'Dark theme', exact: true }).click();
  await page.getByRole('button', { name: 'Open screens', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCSS('background-color', 'rgb(24, 24, 27)');
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('retained draft, close confirmation, focus and accessible switcher', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Screens', exact: true }).getByRole('button', { name: 'Notes', exact: true }).click();
  await page.getByLabel('Draft').fill('My retained draft');
  await page.getByRole('navigation', { name: 'Screens', exact: true }).getByRole('button', { name: 'Activity' }).click();
  await page.getByRole('button', { name: 'Count 0', exact: true }).click();
  await page.getByRole('tab', { name: 'Notes' }).click();
  await expect(page.getByLabel('Draft')).toHaveValue('My retained draft');
  await expect(page.locator('[role="tabpanel"][hidden]').first()).toHaveAttribute('inert', '');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Close Notes', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Notes' })).toBeVisible();
  await page.getByRole('button', { name: 'Open screens', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Notes', exact: true })).toBeFocused();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.keyboard.press('ArrowRight');
  await expect(dialog.getByRole('button', { name: 'Activity', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('button', { name: 'Count 1', exact: true })).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Close Notes', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Notes' })).toHaveCount(0);
  await page.getByRole('navigation', { name: 'Screens', exact: true }).getByRole('button', { name: 'Notes' }).click();
  await expect(page.getByLabel('Draft')).toHaveValue('');
});
test('keyboard navigation, IME and editable shortcut exclusion', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('navigation', { name: 'Screens', exact: true }).getByRole('button', { name: 'Notes', exact: true }).click();
  await page.getByRole('navigation', { name: 'Screens', exact: true }).getByRole('button', { name: 'Activity' }).click();
  const counter = page.getByRole('tab', { name: 'Activity' }); await counter.focus();
  await page.keyboard.press('ArrowLeft'); await expect(page.getByRole('tab', { name: 'Notes' })).toBeFocused();
  await expect(counter).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Enter');
  await page.getByLabel('Draft').focus(); await page.keyboard.press('Alt+q');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const notes = page.getByRole('tab', { name: 'Notes' }); await notes.focus();
  await notes.dispatchEvent('keydown', { key: 'q', altKey: true, isComposing: true });
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.keyboard.press('Alt+3'); await expect(counter).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Alt+q'); await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Activity', exact: true })).toBeFocused();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeHidden();
  await expect(counter).toBeFocused();
});
