import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('retained draft, close confirmation, focus and accessible switcher', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Draft').fill('My retained draft');
  await page.getByRole('navigation').getByRole('button', { name: 'Counter' }).click();
  await page.getByRole('button', { name: 'Count 0', exact: true }).click();
  await page.getByRole('tab', { name: 'Notes' }).click();
  await expect(page.getByLabel('Draft')).toHaveValue('My retained draft');
  await expect(page.locator('[role="tabpanel"][hidden]')).toHaveAttribute('inert', '');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Close Notes', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Notes' })).toBeVisible();
  await page.getByRole('button', { name: 'Switch screens', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Notes', exact: true })).toBeFocused();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.keyboard.press('ArrowRight');
  await expect(dialog.getByRole('button', { name: 'Counter', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(dialog).toBeHidden();
  await expect(page.getByRole('button', { name: 'Count 1', exact: true })).toBeVisible();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Close Notes', exact: true }).click();
  await expect(page.getByRole('tab', { name: 'Notes' })).toHaveCount(0);
  await page.getByRole('navigation').getByRole('button', { name: 'Notes' }).click();
  await expect(page.getByLabel('Draft')).toHaveValue('');
});
test('keyboard navigation, IME and editable shortcut exclusion', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('navigation').getByRole('button', { name: 'Counter' }).click();
  const counter = page.getByRole('tab', { name: 'Counter' }); await counter.focus();
  await page.keyboard.press('ArrowLeft'); await expect(page.getByRole('tab', { name: 'Notes' })).toBeFocused();
  await expect(counter).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Enter');
  await page.getByLabel('Draft').focus(); await page.keyboard.press('Alt+q');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const notes = page.getByRole('tab', { name: 'Notes' }); await notes.focus();
  await notes.dispatchEvent('keydown', { key: 'q', altKey: true, isComposing: true });
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.keyboard.press('Alt+2'); await expect(counter).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Alt+q'); await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Counter', exact: true })).toBeFocused();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toBeHidden();
  await expect(counter).toBeFocused();
});
