import { defineComponent, h, provide, inject, shallowRef, computed, onMounted, onUnmounted, watchEffect, useId, type Component, type InjectionKey, type Ref, type VNodeChild } from 'vue';
import { Tabs } from '@ark-ui/vue/tabs';
import { Dialog } from '@ark-ui/vue/dialog';
import { ark } from '@ark-ui/vue/factory';
import { LocaleProvider } from '@ark-ui/vue/locale';
import { createWorkspace, type Options, type Result, type Screen, type Snapshot, type Tab as CoreTab, type WorkspaceController } from './core';

export interface WorkspaceScreen extends Screen { component: Component }
export interface WorkspaceMenuItem { id: string; label?: string }
export interface WorkspaceLabels { menu: string; tabs: string; switcher: string; close: (title: string) => string; dismiss: string; empty: string; limit: string; denied: string; error: string }
const defaults: WorkspaceLabels = { menu: 'Screens', tabs: 'Open screens', switcher: 'Switch screens', close: title => `Close ${title}`, dismiss: 'Close switcher', empty: 'Choose a screen', limit: 'Maximum open screens reached', denied: 'Screen transition cancelled', error: 'Screen transition failed' };
export type WorkspacePart = 'root' | 'menu' | 'toolbar' | 'tabs' | 'tab' | 'close' | 'panel' | 'status' | 'overlay' | 'positioner' | 'switcher' | 'choices';
export interface WorkspacePresentation {
  screens: readonly WorkspaceScreen[]; menus?: readonly WorkspaceMenuItem[]; menu?: boolean; class?: string; dir?: 'ltr' | 'rtl'; labels?: Partial<WorkspaceLabels>; unstyled?: boolean; classNames?: Partial<Record<WorkspacePart, string>>;
  shortcuts?: boolean | { switcher?: string | false; slots?: readonly (string | false)[] }; onResult?: (result: Result) => void; onError?: (error: unknown) => void;
  slots?: { menu?: (api: WorkspaceController) => VNodeChild; tabLabel?: (screen: WorkspaceScreen, tab: CoreTab) => VNodeChild; switcherItem?: (screen: WorkspaceScreen, tab: CoreTab) => VNodeChild; preview?: (screen: WorkspaceScreen) => VNodeChild; empty?: () => VNodeChild };
}
type Standalone = Omit<Options, 'screens'> & { controller?: never; defaultScreen?: string };
type Controlled = { controller: WorkspaceController; defaultScreen?: never; maxTabs?: never; beforeActivate?: never; beforeClose?: never; onChange?: never };
export type WorkspaceProps = WorkspacePresentation & (Standalone | Controlled);
interface Parts { api: WorkspaceController; state: Ref<Snapshot>; props: WorkspaceProps; labels: () => WorkspaceLabels; screen: (id: string) => WorkspaceScreen; cls: (part: WorkspacePart) => string | undefined; run: (task: Promise<Result>, focus?: boolean) => Promise<Result | undefined>; status: Ref<string>; root: Ref<HTMLDivElement | null>; opener: Ref<HTMLElement | null>; showSwitcher: () => void; prefix: string }
const Context: InjectionKey<Parts> = Symbol('Workspace');
const PageContext: InjectionKey<{ id: string; active: Readonly<Ref<boolean>> }> = Symbol('WorkspacePage');
function useParts() { const c = inject(Context); if (!c) throw new Error('Workspace parts require WorkspaceProvider'); return c; }
export function useWorkspace() { return useParts().api; }
export function useWorkspaceState() { const state = useParts().state; return computed(() => state.value); }

export function useWorkspacePage() { const page = inject(PageContext); if (!page) throw new Error('useWorkspacePage requires a workspace screen'); return page; }
/** Reactive values read by the effect are tracked; cleanup runs on deactivation and unmount. */
export function useActiveEffect(effect: () => void | (() => void)) { const page = useWorkspacePage(); return watchEffect(onCleanup => { if (page.active.value) { const cleanup = effect(); if (cleanup) onCleanup(cleanup); } }); }
function matches(e: KeyboardEvent, shortcut: string | false | undefined) { if (!shortcut) return false; const keys = shortcut.toLowerCase().split('+'); return e.key.toLowerCase() === keys.at(-1) && e.altKey === keys.includes('alt') && e.ctrlKey === keys.includes('ctrl') && e.metaKey === keys.includes('meta') && e.shiftKey === keys.includes('shift'); }
const propNames = ['screens', 'menus', 'menu', 'class', 'dir', 'labels', 'unstyled', 'classNames', 'shortcuts', 'onResult', 'onError', 'slots', 'controller', 'defaultScreen', 'maxTabs', 'beforeActivate', 'beforeClose', 'onChange'] as const;

/** The registry and controller options are construction-time; remount for a new app identity. */
export const WorkspaceProvider = defineComponent((props: WorkspaceProps, { slots }) => {
  const api = props.controller ?? createWorkspace(props); const registry = new Map(props.screens.map(s => [s.id, s]));
  if (registry.size !== props.screens.length || api.getScreens().length !== registry.size || api.getScreens().some(s => !registry.has(s.id))) throw new Error('Controller and component screen registries must match');
  if (props.menus?.some(m => !registry.has(m.id))) throw new Error('Menu references an unknown screen');
  const state = shallowRef(api.getSnapshot()); const direction = shallowRef<'ltr' | 'rtl'>('ltr'); const status = shallowRef(''); const root = shallowRef<HTMLDivElement | null>(null); const opener = shallowRef<HTMLElement | null>(null); const prefix = `ws-${useId()}`;
  let unsubscribe: (() => void) | undefined; onMounted(() => { unsubscribe = api.subscribe(s => { state.value = s; }); state.value = api.getSnapshot(); }); onUnmounted(() => unsubscribe?.());
  const labels = () => ({ ...defaults, ...props.labels }); const cls = (part: WorkspacePart) => [props.unstyled ? '' : part === 'root' ? 'workspace' : `workspace-${part}`, props.classNames?.[part]].filter(Boolean).join(' ') || undefined;
  async function run(task: Promise<Result>, focus = false) { try { const result = await task; props.onResult?.(result); status.value = result === 'limit' ? labels().limit : result === 'denied' || result === 'cancelled' ? labels().denied : ''; if (result === 'ok' && focus) queueMicrotask(() => root.value?.querySelector<HTMLElement>('[role="tab"][aria-selected="true"]')?.focus()); return result; } catch (error) { status.value = labels().error; props.onError?.(error); } }
  function showSwitcher() { opener.value = document.activeElement instanceof HTMLElement ? document.activeElement : null; api.showSwitcher(); }
  let cleanEvents: (() => void) | undefined; let directionObserver: MutationObserver | undefined;
  onMounted(() => {
    if (props.defaultScreen) void run(api.open(props.defaultScreen)); const element = root.value; if (!element) return; const updateDirection = () => { direction.value = getComputedStyle(element.parentElement ?? element).direction === 'rtl' ? 'rtl' : 'ltr'; }; updateDirection(); directionObserver = new MutationObserver(updateDirection); directionObserver.observe(document.documentElement, { subtree: true, attributes: true, attributeFilter: ['dir'] }); let composing = false;
    const keydown = (e: KeyboardEvent) => { if (props.shortcuts === false || composing || e.isComposing || e.keyCode === 229 || e.repeat || e.defaultPrevented || state.value.switcherOpen) return; if (e.target instanceof Element && e.target.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"]),[role="textbox"],[role="combobox"],[role="dialog"],[role="alertdialog"]')) return; if (document.querySelector('[aria-modal="true"]')) return; const config = typeof props.shortcuts === 'object' ? props.shortcuts : undefined; if (matches(e, config?.switcher ?? 'Alt+q')) { e.preventDefault(); showSwitcher(); } else { const tab = state.value.tabs.find(t => matches(e, config?.slots ? config.slots[t.slot - 1] : t.slot <= 9 ? `Alt+${t.slot}` : false)); if (tab) { e.preventDefault(); void run(api.select(tab.id), true); } } };
    const start = () => { composing = true; }; const end = () => { composing = false; }; element.addEventListener('keydown', keydown); element.addEventListener('compositionstart', start); element.addEventListener('compositionend', end); cleanEvents = () => { element.removeEventListener('keydown', keydown); element.removeEventListener('compositionstart', start); element.removeEventListener('compositionend', end); };
  }); onUnmounted(() => { cleanEvents?.(); directionObserver?.disconnect(); });
  provide(Context, { api, state, props, labels, cls, run, status, root, opener, showSwitcher, prefix, screen: id => registry.get(id)! });
  return () => h(LocaleProvider, { locale: (props.dir ?? direction.value) === 'rtl' ? 'ar' : 'en' }, { default: () => h(Tabs.Root, { ref: (instance: unknown) => { root.value = instance instanceof HTMLElement ? instance as HTMLDivElement : (instance as { $el?: HTMLDivElement } | null)?.$el ?? null; }, id: prefix, dir: props.dir ?? direction.value, modelValue: state.value.activeId ?? '', activationMode: 'manual', 'onUpdate:modelValue': (value: string) => { void run(api.select(value)); }, lazyMount: false, unmountOnExit: false, 'data-workspace-part': 'root', class: [cls('root'), props.class].filter(Boolean).join(' ') }, { default: () => slots.default?.() }) });
}, { name: 'WorkspaceProvider', props: [...propNames] });
export const WorkspaceMenu = defineComponent({ name: 'WorkspaceMenu', setup() { const c = useParts(); return () => h('nav', { 'data-workspace-part': 'menu', 'aria-label': c.labels().menu, class: c.cls('menu') }, c.props.slots?.menu?.(c.api) ?? (c.props.menus ?? c.props.screens.map(s => ({ id: s.id, label: s.title }))).map(m => h('button', { key: m.id, type: 'button', onClick: () => { void c.run(c.api.open(m.id)); } }, m.label ?? c.screen(m.id).title))); } });
export const WorkspaceTabList = defineComponent({ name: 'WorkspaceTabList', inheritAttrs: false, setup(_, { slots, attrs }) {
  const c = useParts();
  return () => {
    const listProps = { ...attrs, 'data-workspace-part': 'tabs', 'aria-label': c.labels().tabs, class: attrs.class ?? c.cls('tabs') };
    if (slots.default) return h(Tabs.List, listProps, { default: slots.default });
    return h('div', { class: c.cls('tabs'), style: { display: 'grid', gridTemplateColumns: `repeat(${Math.max(1, c.state.value.tabs.length * 2)}, max-content)`, overflowX: 'auto', gap: 0 } }, [
      h(Tabs.List, { ...listProps, class: attrs.class, style: [attrs.style, { display: 'contents' }] }, { default: () => c.state.value.tabs.map((t, index) => h('div', { key: t.instance, role: 'presentation', class: c.cls('tab'), 'data-active': c.state.value.activeId === t.id, style: { display: 'contents' } }, [h(WorkspaceTab, { id: t.id, style: { gridRow: 1, gridColumn: index * 2 + 1 } })])) }),
      ...c.state.value.tabs.map((t, index) => h(WorkspaceCloseButton, { key: t.instance, id: t.id, style: { gridRow: 1, gridColumn: index * 2 + 2, marginInlineEnd: '.5rem' } })),
    ]);
  };
} });export const WorkspaceTab = defineComponent({ name: 'WorkspaceTab', inheritAttrs: false, props: { id: { type: String, required: true } }, setup(props, { slots, attrs }) { const c = useParts(); return () => h(Tabs.Trigger, { ...attrs, value: props.id, class: attrs.class ?? c.cls('tab'), 'data-workspace-part': 'tab', onKeydown: (e: KeyboardEvent) => { (attrs.onKeydown as ((e: KeyboardEvent) => void) | undefined)?.(e); if (!e.defaultPrevented && e.key === 'Delete' && !e.isComposing) { e.preventDefault(); void c.run(c.api.close(props.id), true); } } }, { default: () => slots.default?.() ?? c.props.slots?.tabLabel?.(c.screen(props.id), c.state.value.tabs.find(t => t.id === props.id)!) ?? c.screen(props.id).title }); } });
export const WorkspaceCloseButton = defineComponent({ name: 'WorkspaceCloseButton', inheritAttrs: false, props: { id: { type: String, required: true } }, setup(props, { slots, attrs }) { const c = useParts(); return () => h(ark.button, { ...attrs, type: 'button', 'data-workspace-part': 'close', class: attrs.class ?? c.cls('close'), 'aria-label': c.labels().close(c.screen(props.id).title), onClick: (e: MouseEvent) => { (attrs.onClick as ((e: MouseEvent) => void) | undefined)?.(e); if (!e.defaultPrevented) void c.run(c.api.close(props.id), true); } }, { default: () => slots.default?.() ?? '×' }); } });
const Page = defineComponent({ props: { id: { type: String, required: true } }, setup(props) { const c = useParts(); const active = computed(() => c.state.value.activeId === props.id); provide(PageContext, { id: props.id, active }); return () => h(Tabs.Content, { value: props.id, 'data-workspace-part': 'panel', class: c.cls('panel'), style: active.value ? undefined : { display: 'none' }, hidden: !active.value, inert: !active.value }, { default: () => h(c.screen(props.id).component) }); } });
export const WorkspacePanels = defineComponent({ name: 'WorkspacePanels', setup() { const c = useParts(); return () => c.state.value.tabs.length ? c.state.value.tabs.map(t => h(Page, { key: t.instance, id: t.id })) : c.props.slots?.empty?.() ?? h('p', c.labels().empty); } });
export const WorkspaceStatus = defineComponent({ name: 'WorkspaceStatus', setup() { const c = useParts(); return () => h('div', { role: 'status', 'aria-live': 'polite', hidden: c.state.value.switcherOpen, 'data-workspace-part': 'status', class: c.cls('status') }, c.status.value); } });
export const WorkspaceSwitcherTrigger = defineComponent({ name: 'WorkspaceSwitcherTrigger', inheritAttrs: false, setup(_, { slots, attrs }) { const c = useParts(); return () => h(ark.button, { ...attrs, type: 'button', 'aria-haspopup': 'dialog', disabled: !c.state.value.tabs.length, 'data-workspace-part': 'switcher-trigger', onClick: (e: MouseEvent) => { (attrs.onClick as ((e: MouseEvent) => void) | undefined)?.(e); if (!e.defaultPrevented) c.showSwitcher(); } }, { default: () => slots.default?.() ?? c.labels().switcher }); } });
export const WorkspaceSwitcher = defineComponent({ name: 'WorkspaceSwitcher', setup(_, { slots }) {
  const c = useParts();
  return () => h(Dialog.Root, { id: `${c.prefix}-switcher`, open: c.state.value.switcherOpen, 'onUpdate:open': (open: boolean) => open ? c.api.showSwitcher() : c.api.hideSwitcher(), initialFocusEl: () => document.getElementById(`${c.prefix}-choice-${c.state.value.activeId}`), finalFocusEl: () => { const opener = c.opener.value; return opener?.isConnected && !opener.closest('[hidden],[inert]') ? opener : c.root.value?.querySelector<HTMLElement>('[role="tab"][aria-selected="true"]') ?? null; }, modal: true, trapFocus: true, preventScroll: true, lazyMount: true, unmountOnExit: true }, { default: () => [h(Dialog.Backdrop, { class: c.cls('overlay') }), h(Dialog.Positioner, { class: c.cls('positioner') }, { default: () => h(Dialog.Content, { class: c.cls('switcher'), 'data-workspace-part': 'switcher' }, { default: () => [h(Dialog.Title, {}, { default: () => c.labels().switcher }), h(Dialog.Description, {}, { default: () => c.labels().tabs }), h('div', { role: 'status', 'aria-live': 'polite', 'data-workspace-part': 'switcher-status', class: c.cls('status') }, c.status.value), slots.default?.() ?? h('div', { class: c.cls('choices'), onKeydown: (e: KeyboardEvent) => { if (e.isComposing) return; const items = Array.from((e.currentTarget as HTMLElement).querySelectorAll<HTMLButtonElement>('[data-workspace-choice]')); const index = items.indexOf(e.target as HTMLButtonElement); if (index < 0) return; const next = e.key === 'Home' ? 0 : e.key === 'End' ? items.length - 1 : ['ArrowDown', 'ArrowRight'].includes(e.key) ? (index + 1) % items.length : ['ArrowUp', 'ArrowLeft'].includes(e.key) ? (index + items.length - 1) % items.length : -1; if (next >= 0) { e.preventDefault(); items[next]?.focus(); } } }, c.state.value.tabs.map(t => h('button', { key: t.id, type: 'button', 'data-workspace-choice': '', id: `${c.prefix}-choice-${t.id}`, 'aria-current': c.state.value.activeId === t.id ? 'true' : undefined, onClick: () => { void c.run(c.api.select(t.id)).then(result => { if (result === 'ok') c.api.hideSwitcher(); }); } }, [c.props.slots?.preview && h('div', { 'aria-hidden': true, inert: true }, [c.props.slots.preview(c.screen(t.id))]), c.props.slots?.switcherItem?.(c.screen(t.id), t) ?? c.screen(t.id).title]))), h(Dialog.CloseTrigger, {}, { default: () => c.labels().dismiss })] }) })] });
} });
export const Workspace = defineComponent((props: WorkspaceProps, { slots }) => () => h(WorkspaceProvider, props, { default: () => [slots.default?.(), props.menu !== false && h(WorkspaceMenu), h('div', { class: props.unstyled ? props.classNames?.toolbar : `workspace-toolbar ${props.classNames?.toolbar ?? ''}` }, [h(WorkspaceSwitcherTrigger), h(WorkspaceTabList)]), h(WorkspaceStatus), h(WorkspacePanels), h(WorkspaceSwitcher)] }), { name: 'Workspace', props: [...propNames] });
export { WorkspaceProvider as Provider, WorkspaceTabList as TabList, WorkspaceTab as Tab, WorkspaceCloseButton as CloseButton, WorkspacePanels as Panels, WorkspaceSwitcher as Switcher, WorkspaceSwitcherTrigger as SwitcherTrigger };
